### ISSUE TITLE
🔧👀Paratii.js Developer Preview release 🚀

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-js#210]
> 🔧👀 A first public release of the Paratii.js: the easiest way for developers to interact with Paratii's distributed video platform. ⚡

# 🌍 What's left to release

- [x] Update npm instructions (currrenly as "We intend to provide the package on npmjs.org for easy download once it is in a more stable...").
- [x] Upload function is not local (gotta be).
- [x] Have a polished example in ipfsSchema.
- [ ] ParatiiIPFSLocal should be under the ParatiiIPFS namespace - one needs a local instance to start interacting anyway. ParatiiIPFSRemote remains on its own.
- [x] Separate the transcoder commands (i.e. for it to be easier to transcode & stream audio, as we spoke on the call - this can be better specified @jellegerbrandy).
- [x] Have a 'const Paratii = default Paratii' so you can just upload, search, do very high level stuff (easyness along the lines of how IPFS maps down commands like `add`)
- [x] Better document event emmiters.
- [x] Polish the TCR part -> add/delete.

_Also_:
- [x] Add a bit more technical indications on the "simple ideas for hacks".
- [x] Add a bit more discursive text and set up instructions on homepage https://github.com/Paratii-Video/paratii-js/issues/180
- [x] Add a tutorials tab https://github.com/Paratii-Video/paratii-js/issues/207
- [x] Record a simple walkthrough.
- [x] Change the docs theme https://github.com/Paratii-Video/paratii-js/issues/208 

# 🔦 Highlights

### TO WRITE
**TO WRITE**

# ✅ Release Checklist

- **Documentation** (not the lib's one)
  - [ ] Ensure that README.md is up to date
  - [x] Create the release issue

- **Communication**
   - [ ] Medium post (developer preview)
   - [ ] Twitter
   - [ ] Telegram
   - [ ] Reddit
   - [ ] Facebook

# 🙌🏽 Want to contribute?
Please first have a quick look at our contribution guidelines [here](https://github.com/Paratii-Video/wiki/blob/master/CONTRIBUTING.md). Be on the lookout for issues labeled with something that catches your eyes and sparks your interest. And feel free to drop a line on [gitter](https://gitter.im/Paratii-Video) about anything relevant - from a UX suggestion to a bug fix.

**Comment by LorenzoAlluminio** [comment]
I'm adding the remaining points from my list so we can all look here

[ ] - document returned objects when useful
[ ] - define userSchema for paratii.core.users.create()

**Comment by felipegaucho** [comment]
big kudos to all involved in this milestone 👊
